name: Health Check

#on:
#  schedule:
#    - cron: "*/60 * * * *"
#  workflow_dispatch:

jobs:
  check_health:
    runs-on: ubuntu-latest
    steps:
      - name: Check production URL health
        uses: Jtalk/url-health-check-action@v3
        with:
          url: "https://full-stack-open-pokedex-5oqm.onrender.com/"
          max-attempts: 5
          retry-delay: 10s

      - name: Notify Discord on failure
        if: ${{ failure() }}
        uses: rjstone/discord-webhook-notify@v2
        with:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          text: |
            Health Check Failed!
            URL: https://full-stack-open-pokedex-5oqm.onrender.com/
